#!/bin/bash
# script_lib.sh -- shared functions for all nsh-vault-deploy scripts
#
# Source this near the top of every script:
#   SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
#   source "$SCRIPT_DIR/../../script_lib.sh"

VAULT_CONTAINER="${VAULT_CONTAINER:-vault}"
VAULT_ADDR="${VAULT_ADDR:-http://127.0.0.1:8100}"


log()
{
  echo
  echo "$@"
  echo
}


header()
{
  echo
  echo "----------------------------------------"
  echo "$@"
  echo "----------------------------------------"
  echo
}


GetInput()
{
  local VAR_NAME="$1"
  local PROMPT="$2"
  local DEFAULT="${!VAR_NAME:-}"
  local VALUE

  if [ -z "$PROMPT" ]; then
    PROMPT="$VAR_NAME"
  fi

  if [ -n "$DEFAULT" ]; then
    read -r -p "$PROMPT [$DEFAULT]: " VALUE

    if [ -z "$VALUE" ]; then
      VALUE="$DEFAULT"
    fi
  else
    read -r -p "$PROMPT: " VALUE
  fi

  printf -v "$VAR_NAME" "%s" "$VALUE"
}


# SetupVaultCLI -- define a vault() shell function if vault binary is not installed locally.
# The function passes VAULT_ADDR and VAULT_TOKEN into the container via docker exec.
SetupVaultCLI()
{
  if ! command -v vault >/dev/null 2>&1; then
    vault()
    {
      docker exec -i \
        -e VAULT_ADDR="$VAULT_ADDR" \
        -e VAULT_TOKEN="$VAULT_TOKEN" \
        "$VAULT_CONTAINER" vault "$@"
    }
  fi
}


# LoadVaultToken -- load root token from vault-init.json into VAULT_TOKEN if not already set.
# Usage: LoadVaultToken "$INIT_FILE"
LoadVaultToken()
{
  local INIT_FILE_PATH="$1"

  if [ -z "${VAULT_TOKEN:-}" ]; then
    if [ -f "$INIT_FILE_PATH" ]; then
      VAULT_TOKEN=$(jq -r '.root_token' "$INIT_FILE_PATH")
    fi
  fi
}


# LoadEnvFile -- load variables from a .env file (key=value format, one per line)
# Skips lines that start with # (comments) and empty lines.
# Usage: LoadEnvFile "$ENV_FILE"
# Example .env file:
#   VAULT_ADDR=http://127.0.0.1:8100
#   VAULT_API_ADDR=https://vault.example.com
#   VAULT_DOMAIN=example.com
LoadEnvFile()
{
  local ENV_FILE="$1"

  if [ -f "$ENV_FILE" ]; then
    while IFS='=' read -r key value; do
      # Skip comments and empty lines
      [[ "$key" =~ ^#.*$ ]] && continue
      [ -z "$key" ] && continue

      # Only set if not already set by environment
      if [ -z "${!key:-}" ]; then
        eval "${key}=${value}"
        export "${key}"
      fi
    done < "$ENV_FILE"
  fi
}


# SaveEnvFile -- save all provisioner variables to a .env file for later reuse
# Usage: SaveEnvFile "$ENV_FILE" [VAR1] [VAR2] ...
# Example:
#   SaveEnvFile "provisioners.env" VAULT_ADDR VAULT_API_ADDR VAULT_DOMAIN
SaveEnvFile()
{
  local ENV_FILE="$1"
  shift  # remove first arg

  {
    echo "# Vault Provisioner Configuration"
    echo "# Generated by provisioner scripts"
    echo "# Source this to avoid re-entering variables on each run:"
    echo "#   source provisioners.env"
    echo
    for var in "$@"; do
      if [ -n "${!var:-}" ]; then
        echo "${var}=${!var}"
      fi
    done
  } > "$ENV_FILE"

  chmod 600 "$ENV_FILE"
  echo "Saved configuration to: $ENV_FILE"
}
