#!/bin/bash
# script_lib.sh -- shared functions for all nsh-vault-deploy scripts
#
# Source this near the top of every script:
#   SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
#   source "$SCRIPT_DIR/../../script_lib.sh"

VAULT_CONTAINER="${VAULT_CONTAINER:-vault}"
VAULT_ADDR="${VAULT_ADDR:-http://127.0.0.1:8100}"


log()
{
  echo
  echo "$@"
  echo
}


header()
{
  echo
  echo "----------------------------------------"
  echo "$@"
  echo "----------------------------------------"
  echo
}


# GetInput -- prompt user for input, respecting INTERACTIVE mode
# Modes:
#   INTERACTIVE=true  (1) - always prompt, even if variable is set
#   INTERACTIVE=false (0) - only prompt if variable is empty
# Usage: GetInput VAR_NAME "Prompt text"
GetInput()
{
  local VAR_NAME="$1"
  local PROMPT="$2"
  local DEFAULT="${!VAR_NAME:-}"
  local VALUE

  if [ -z "$PROMPT" ]; then
    PROMPT="$VAR_NAME"
  fi

  # If INTERACTIVE=false (non-interactive mode) and variable is set, skip prompt
  if [ "${INTERACTIVE:-true}" = "false" ] && [ -n "$DEFAULT" ]; then
    return 0
  fi

  # Interactive prompt
  if [ -n "$DEFAULT" ]; then
    read -r -p "$PROMPT [$DEFAULT]: " VALUE

    if [ -z "$VALUE" ]; then
      VALUE="$DEFAULT"
    fi
  else
    read -r -p "$PROMPT: " VALUE
  fi

  printf -v "$VAR_NAME" "%s" "$VALUE"
}


# SetupVaultCLI -- define a vault() shell function if vault binary is not installed locally.
# The function passes VAULT_ADDR and VAULT_TOKEN into the container via docker exec.
SetupVaultCLI()
{
  if ! command -v vault >/dev/null 2>&1; then
    vault()
    {
      docker exec -i \
        -e VAULT_ADDR="$VAULT_ADDR" \
        -e VAULT_TOKEN="$VAULT_TOKEN" \
        "$VAULT_CONTAINER" vault "$@"
    }
  fi
}


# LoadVaultToken -- load root token from vault-init.json into VAULT_TOKEN if not already set.
# Usage: LoadVaultToken "$INIT_FILE"
LoadVaultToken()
{
  local INIT_FILE_PATH="$1"

  if [ -z "${VAULT_TOKEN:-}" ]; then
    if [ -f "$INIT_FILE_PATH" ]; then
      VAULT_TOKEN=$(jq -r '.root_token' "$INIT_FILE_PATH")
    fi
  fi
}


# LoadEnvFile -- load variables from a .env file (key=value format, one per line)
# Skips lines that start with # (comments) and empty lines.
# Usage: LoadEnvFile "$ENV_FILE"
# Example .env file:
#   VAULT_ADDR=http://127.0.0.1:8100
#   VAULT_API_ADDR=https://vault.example.com
#   VAULT_DOMAIN=example.com
LoadEnvFile()
{
  local ENV_FILE="$1"

  if [ -f "$ENV_FILE" ]; then
    while IFS='=' read -r key value; do
      # Skip comments and empty lines
      [[ "$key" =~ ^#.*$ ]] && continue
      [ -z "$key" ] && continue

      # Only set if not already set by environment
      if [ -z "${!key:-}" ]; then
        eval "${key}=${value}"
        export "${key}"
      fi
    done < "$ENV_FILE"
  fi
}


# SaveEnvFile -- save all provisioner variables to a .env file for later reuse
# Usage: SaveEnvFile "$ENV_FILE" [VAR1] [VAR2] ...
# Example:
#   SaveEnvFile "provisioners.env" VAULT_ADDR VAULT_API_ADDR VAULT_DOMAIN
SaveEnvFile()
{
  local ENV_FILE="$1"
  shift  # remove first arg

  {
    echo "# Vault Provisioner Configuration"
    echo "# Generated by provisioner scripts"
    echo "# Source this to avoid re-entering variables on each run:"
    echo "#   source provisioners.env"
    echo
    for var in "$@"; do
      if [ -n "${!var:-}" ]; then
        echo "${var}=${!var}"
      fi
    done
  } > "$ENV_FILE"

  chmod 600 "$ENV_FILE"
  echo "Saved configuration to: $ENV_FILE"
}


# pause_for_continue -- pause and wait for user to press any key (for guided tours)
# Usage: pause_for_continue "Press any key to continue..."
pause_for_continue()
{
  local PROMPT="${1:-Press any key to continue...}"
  echo
  read -r -s -n 1 -p "$PROMPT"
  echo
  echo
}


# explain -- display explanation text for guided tour
# Usage: explain "Here's what just happened..."
explain()
{
  echo "$@"
  echo
}


# show_verify -- display verification commands for a step
# Usage: show_verify "vault read pki/config/urls" "vault list pki/roles"
show_verify()
{
  echo
  echo "Verify this step with:"
  for cmd in "$@"; do
    echo "  $cmd"
  done
  echo
}


# display_root_token -- display root token for UI login
# Usage: display_root_token
display_root_token()
{
  local INIT_FILE="${1:-.}"
  if [ -f "$INIT_FILE" ]; then
    local ROOT_TOKEN=$(jq -r '.root_token' "$INIT_FILE")
    echo
    header "ROOT TOKEN FOR UI LOGIN"
    if [ -n "${VAULT_API_ADDR:-}" ]; then
      echo "Vault UI: $VAULT_API_ADDR"
    fi
    echo "Token: $ROOT_TOKEN"
    echo
  fi
}


# clear_screen -- clear terminal screen (respects ENABLE_CLEAR setting)
# Set ENABLE_CLEAR=false to disable clearing
# Usage: clear_screen
clear_screen()
{
  if [ "${ENABLE_CLEAR:-true}" != "false" ]; then
    clear
  fi
}
