#!/bin/bash
# setup-config.sh -- Interactive configuration setup
#
# This script prompts for all Vault configuration parameters
# and creates .env file with the values.
#
# Usage:
#   bash setup-config.sh
#
# Then run provisioners:
#   bash setup-provisioners.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/script_lib.sh"

ENV_FILE="${SCRIPT_DIR}/.env"
INTERACTIVE=true

header "Vault Configuration Setup"

echo "This will create .env file with your Vault configuration."
echo "You can override defaults by entering new values, or press Enter to accept defaults."
echo

# Vault Server Setup
header "Vault Server Setup"

VAULT_FQDN="vault.example.com"
GetInput VAULT_FQDN "Vault server FQDN (e.g. vault.company.com)"

VAULT_HTTPS_PORT="443"
GetInput VAULT_HTTPS_PORT "HTTPS port (443 for standard)"

# Auto-generate API_ADDR from FQDN and port
if [ "$VAULT_HTTPS_PORT" = "443" ]; then
  VAULT_API_ADDR="https://${VAULT_FQDN}"
else
  VAULT_API_ADDR="https://${VAULT_FQDN}:${VAULT_HTTPS_PORT}"
fi
GetInput VAULT_API_ADDR "Public Vault API URL"

# Provisioning Configuration
header "Provisioning Configuration"

VAULT_ADDR="http://127.0.0.1:8100"
GetInput VAULT_ADDR "Vault internal address (for provisioning)"

VAULT_DOMAIN="example.com"
GetInput VAULT_DOMAIN "Certificate domain (e.g. company.com)"

# VAULT_TOKEN will be auto-loaded from vault-init.json, but ask anyway
VAULT_TOKEN=""
GetInput VAULT_TOKEN "Root token (leave empty to auto-load from vault-init.json)"


# Summary
header "Configuration Summary"

echo "  VAULT_FQDN          : $VAULT_FQDN"
echo "  VAULT_HTTPS_PORT    : $VAULT_HTTPS_PORT"
echo "  VAULT_API_ADDR      : $VAULT_API_ADDR"
echo "  VAULT_ADDR          : $VAULT_ADDR"
echo "  VAULT_DOMAIN        : $VAULT_DOMAIN"
echo "  VAULT_TOKEN         : ${VAULT_TOKEN:-(will auto-load)}"
echo

read -r -p "Save this configuration? (y/n) " -n 1
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
  echo "Cancelled."
  exit 0
fi

# Save .env
{
  echo "# Vault Configuration"
  echo "# Generated by setup-config.sh"
  echo
  echo "# Vault Server Setup"
  echo "VAULT_FQDN=$VAULT_FQDN"
  echo "VAULT_HTTPS_PORT=$VAULT_HTTPS_PORT"
  echo "VAULT_API_ADDR=$VAULT_API_ADDR"
  echo
  echo "# Provisioning Configuration"
  echo "VAULT_ADDR=$VAULT_ADDR"
  if [ -n "$VAULT_TOKEN" ]; then
    echo "VAULT_TOKEN=$VAULT_TOKEN"
  fi
  echo "VAULT_DOMAIN=$VAULT_DOMAIN"
} > "$ENV_FILE"

chmod 600 "$ENV_FILE"

log "Configuration saved to: $ENV_FILE"

echo
echo "Next steps:"
echo "  ./setup-provisioners.sh      (automated deployment)"
echo "  ./guided-tour.sh             (educational walkthrough)"
echo
