#!/bin/bash
# setup-config.sh -- Interactive configuration setup
#
# This script prompts for all Vault configuration parameters
# and creates .env file with the values.
#
# Usage:
#   bash setup-config.sh
#
# Then run provisioners:
#   bash setup-provisioners.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/script_lib.sh"

ENV_FILE="${SCRIPT_DIR}/.env"
INTERACTIVE=true

header "Vault Configuration Setup"

echo "This will create .env file with your Vault configuration."
echo "You can override defaults by entering new values, or press Enter to accept defaults."
echo

# Vault Server Setup
header "Vault Server Setup"

VAULT_FQDN="vault.example.com"
GetInput VAULT_FQDN "Vault server FQDN (e.g. vault.company.com)"

VAULT_HTTPS_PORT="443"
GetInput VAULT_HTTPS_PORT "HTTPS port (443 for standard)"

# Auto-generate API_ADDR from FQDN and port
if [ "$VAULT_HTTPS_PORT" = "443" ]; then
  VAULT_API_ADDR="https://${VAULT_FQDN}"
else
  VAULT_API_ADDR="https://${VAULT_FQDN}:${VAULT_HTTPS_PORT}"
fi
GetInput VAULT_API_ADDR "Public Vault API URL"

# Provisioning Configuration
header "Provisioning Configuration"

VAULT_ADDR="http://127.0.0.1:8100"
GetInput VAULT_ADDR "Vault internal address (for provisioning)"

VAULT_DOMAIN="example.com"
GetInput VAULT_DOMAIN "Certificate domain (e.g. company.com)"

# VAULT_TOKEN will be auto-loaded from vault-init.json, but ask anyway
VAULT_TOKEN=""
GetInput VAULT_TOKEN "Root token (leave empty to auto-load from vault-init.json)"


# Summary
header "Configuration Summary"

echo "  VAULT_FQDN          : $VAULT_FQDN"
echo "  VAULT_HTTPS_PORT    : $VAULT_HTTPS_PORT"
echo "  VAULT_API_ADDR      : $VAULT_API_ADDR"
echo "  VAULT_ADDR          : $VAULT_ADDR"
echo "  VAULT_DOMAIN        : $VAULT_DOMAIN"
echo "  VAULT_TOKEN         : ${VAULT_TOKEN:-(will auto-load)}"
echo

read -r -p "Save this configuration? (y/n) " -n 1
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
  echo "Cancelled."
  exit 0
fi

# Save .env
{
  echo "# Vault Configuration"
  echo "# Generated by setup-config.sh"
  echo
  echo "# Vault Server Setup"
  echo "VAULT_FQDN=$VAULT_FQDN"
  echo "VAULT_HTTPS_PORT=$VAULT_HTTPS_PORT"
  echo "VAULT_API_ADDR=$VAULT_API_ADDR"
  echo
  echo "# Provisioning Configuration"
  echo "VAULT_ADDR=$VAULT_ADDR"
  if [ -n "$VAULT_TOKEN" ]; then
    echo "VAULT_TOKEN=$VAULT_TOKEN"
  fi
  echo "VAULT_DOMAIN=$VAULT_DOMAIN"
} > "$ENV_FILE"

chmod 600 "$ENV_FILE"

log "Configuration saved to: $ENV_FILE"

# TLS Bootstrap Certificates
header "TLS Bootstrap Certificates"

TLS_DIR="${SCRIPT_DIR}/server/tls"
TLS_CERT="${TLS_DIR}/vault.crt"
TLS_KEY="${TLS_DIR}/vault.key"

if [ -f "$TLS_CERT" ] && [ -f "$TLS_KEY" ]; then
  echo "TLS certificates already exist:"
  echo "  $TLS_CERT"
  echo "  $TLS_KEY"
  echo
  read -r -p "Regenerate TLS certificates? (y/n) " -n 1
  echo
  GENERATE_TLS=$REPLY
else
  echo "No TLS certificates found."
  echo
  read -r -p "Generate bootstrap TLS certificates? (y/n) " -n 1
  echo
  GENERATE_TLS=$REPLY
fi

if [[ $GENERATE_TLS =~ ^[Yy]$ ]]; then
  echo "Generating bootstrap TLS certificates for: $VAULT_FQDN"

  bash "$TLS_DIR/bootstrap.sh" "$VAULT_FQDN"

  echo
  echo "TLS certificates generated:"
  echo "  $TLS_CERT"
  echo "  $TLS_KEY"
  echo
  echo "⚠️  These are TEMPORARY bootstrap certificates (self-signed, 365 days)"
  echo
  echo "If you have your own TLS certificates, replace these files:"
  echo "  - Vault server cert: $TLS_CERT"
  echo "  - Vault server key:  $TLS_KEY"
  echo
  echo "Then restart Vault:"
  echo "  ./start-vault.sh"
  echo
else
  if ! [ -f "$TLS_CERT" ] || ! [ -f "$TLS_KEY" ]; then
    header "ERROR: Missing TLS Certificates"
    echo "TLS certificates are required to start Vault."
    echo
    echo "Provide your own certificates:"
    echo "  cp your-cert.crt $TLS_CERT"
    echo "  cp your-key.key  $TLS_KEY"
    echo
    echo "Or run this script again and choose to generate bootstrap certificates."
    echo
    exit 1
  fi
fi

echo "Next steps:"
echo "  ./start-vault.sh             (start Vault container)"
echo "  ./setup-provisioners.sh      (automated deployment)"
echo "  ./guided-tour.sh             (educational walkthrough)"
echo
