#!/usr/bin/env bash
# create-nginx-role.sh <hostname>
#
# Creates a Vault policy and AppRole scoped to a single server.
# The same command handles regular and wildcard FQDNs — there is no distinction.
#
# Examples:
#   bash init/create-nginx-role.sh nginx01.example.com
#   bash init/create-nginx-role.sh star.example.com

set -euo pipefail

HOSTNAME="${1:?Usage: $0 <hostname>}"
VAULT_ADDR="${VAULT_ADDR:-http://127.0.0.1:8100}"   # internal HTTP port
INIT_FILE="./vault-init.json"

export VAULT_ADDR

if command -v vault >/dev/null 2>&1; then
  vault() { command vault "$@"; }
else
  vault() { docker exec -e VAULT_ADDR="$VAULT_ADDR" -e VAULT_TOKEN="${VAULT_TOKEN:-}" vault vault "$@"; }
fi
export -f vault

if [ -z "${VAULT_TOKEN:-}" ]; then
  if [ -f "$INIT_FILE" ]; then
    VAULT_TOKEN=$(jq -r '.root_token' "$INIT_FILE")
    export VAULT_TOKEN
  else
    echo "ERROR: VAULT_TOKEN not set and $INIT_FILE not found" >&2
    echo "  Either export VAULT_TOKEN or run setup.sh first" >&2
    exit 1
  fi
fi

# Policy and role names use dashes — dots are not valid in some contexts
POLICY_NAME="nginx-$(echo "$HOSTNAME" | tr '.' '-')"
ROLE_NAME="nginx-${HOSTNAME}"

echo "=== Creating role for ${HOSTNAME} ==="

# ── scoped policy (covers both rsa and ecdsa sub-paths) ───────────────────────
vault policy write "$POLICY_NAME" - <<EOF
# Auto-generated by create-nginx-role.sh for ${HOSTNAME}
# Covers secret/certs/${HOSTNAME}/rsa and secret/certs/${HOSTNAME}/ecdsa

path "secret/data/certs/${HOSTNAME}/*" {
  capabilities = ["read"]
}

path "secret/metadata/certs/${HOSTNAME}/*" {
  capabilities = ["read"]
}
EOF
echo "  Policy: $POLICY_NAME"

# ── AppRole ───────────────────────────────────────────────────────────────────
vault write "auth/approle/role/${ROLE_NAME}" \
  token_policies="$POLICY_NAME" \
  token_ttl=2h \
  token_max_ttl=8h \
  secret_id_ttl=0
echo "  AppRole: $ROLE_NAME"

# ── credentials ───────────────────────────────────────────────────────────────
ROLE_ID=$(vault read -field=role_id "auth/approle/role/${ROLE_NAME}/role-id")
SECRET_ID=$(vault write -force -field=secret_id "auth/approle/role/${ROLE_NAME}/secret-id")

CRED_DIR="$(dirname "$0")/../../client/nginx/credentials/${HOSTNAME}"
mkdir -p "$CRED_DIR"
printf '%s' "$ROLE_ID"   > "${CRED_DIR}/role_id"
printf '%s' "$SECRET_ID" > "${CRED_DIR}/secret_id"
chmod 600 "${CRED_DIR}/secret_id"

echo ""
echo "  Credentials: client/nginx/credentials/${HOSTNAME}/"
echo "  Deploy to:   /etc/vault-agent/ on ${HOSTNAME}"
